server:
  port: 8080
  mode: debug
  read_timeout: 30
  write_timeout: 30

database:
  host: ${MYSQLHOST}
  port: ${MYSQLPORT}
  user: ${MYSQLUSER}
  password: FynMYoIscYHvrIFbicdofkkAsIxnlKja
  dbname: ${MYSQL_DATABASE}
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

redis:
  host: ${REDISHOST}
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0
  pool_size: 10
